{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-frictionless
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/frictionless_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/frictionless/frictionless_{{ version }}.tar.gz
  sha256: 6f1b351c1400af19bb12e56c630ee439483814ba41acc4943c19f219d57a4334

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-purrr
    - r-readr >=2.1.0
    - r-yaml
  run:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-purrr
    - r-readr >=2.1.0
    - r-yaml

test:
  commands:
    - $R -e "library('frictionless')"           # [not win]
    - "\"%R%\" -e \"library('frictionless')\""  # [win]

about:
  home: https://github.com/frictionlessdata/frictionless-r, https://docs.ropensci.org/frictionless/
  license: MIT
  summary: Read and write Frictionless Data Packages. A 'Data Package' (<https://specs.frictionlessdata.io/data-package/>) is a simple container format and standard to describe and package a collection of (tabular) data. It is typically used to publish FAIR (<https://www.go-fair.org/fair-principles/>) and open datasets.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - rgaiacs
